### ISSUE TITLE
给的例子的结果不能复现？请问是需要进行什么前置操作吗？

### ISSUE THREAD

**Issue by rainfallLLF** [neukg/TechGPT-2.0#2]
如题，我下载模型后使用demo代码运行（未改动任何参数），运行成功了，但无法复现readme中的给的例子，如三元组抽取，实体抽取等任务，模型的似乎不理解任务类型，其给的答复只是类似CHAT一样，用一段文本“答复”了我的问题，无法复现readme中的给的例子。请问是需要微调吗？还是其它操作？能否帮忙解答下，盼复！

**Comment by 1828688173** [comment]
我也是，alpaca和atom两类都尝试运行了下，没能复现案例，三元组抽取反而没有一代的效果好

**Comment by rainfallLLF** [comment]
> 我也是，alpaca和atom两类都尝试运行了下，没能复现案例，三元组抽取反而没有一代的效果好

三元组抽取，一代的我也试用了，也达不到其readme中的效果，你的如何？

**Comment by 1828688173** [comment]
一代的调参后可以达到不错的效果

**Comment by rainfallLLF** [comment]
> 一代的调参后可以达到不错的效果

怎么调参，求指教，多谢

**Comment by Quant2017** [comment]
三元组抽取感觉根本用不了

**Comment by rainfallLLF** [comment]
> 三元组抽取感觉根本用不了

一个月了，作者无答复，而我还一直在等

**Comment by wujiaxin-study** [comment]
> 一代的调参后可以达到不错的效果

求指教 非常感谢

**Comment by 1828688173** [comment]
> 一代的调参后可以达到不错的效果

[KnowledgeExtraction]
top_k = 30
top_p = 0.75
num_beams = 1
temperature = 0.75
repetition_penalty = 1.0
max_new_tokens = 512
bos_token_id = 1
pad_token_id = 0
eos_token_id = 2
min_length = 200
max_length = 400

**Comment by wujiaxin-study** [comment]
> > 一代的调参后可以达到不错的效果
> 
> [KnowledgeExtraction] top_k = 30 top_p = 0.75 num_beams = 1 temperature = 0.75 repetition_penalty = 1.0 max_new_tokens = 512 bos_token_id = 1 pad_token_id = 0 eos_token_id = 2 min_length = 200 max_length = 400

非常感谢您的回答 效果提升了很多

**Comment by wujiaxin-study** [comment]
> > 一代的调参后可以达到不错的效果
> 
> [KnowledgeExtraction] top_k = 30 top_p = 0.75 num_beams = 1 temperature = 0.75 repetition_penalty = 1.0 max_new_tokens = 512 bos_token_id = 1 pad_token_id = 0 eos_token_id = 2 min_length = 200 max_length = 400

您好  我想请问一下  您有没有把lora权重与 alpace或者atom权重合并  可以指导一下如何合并嘛   万分感谢

**Comment by neukg** [comment]
目前已经更新了web-Gui的代码方便各位部署，atom与alpaca的参数也已经更新。
对于Alpaca，我建议将重复惩罚设为1、最大生成token尽量减少，此三种模型中Alpaca表现欠佳。
对于Atom与Qwen，则可以按照默认参数测试。
