### ISSUE TITLE
【数据集】请问训练数据集格式是怎么样的或者有开源数据集准备吗。

### ISSUE THREAD

**Issue by ninghongbo123** [neukg/TechGPT-2.0#4]
请问训练数据集格式是怎么样的或者有开源数据集准备吗。

**Comment by wenzezhang** [comment]
同问

**Comment by neukg** [comment]
您好，目前prompt格式可以参考2.0项目中的web-gui中的Prompt，数据集格式则可以参考Qwen-1.5-7b-chat、Atom-7b-chat（https://github.com/LlamaFamily/Llama-Chinese）、[Chinese-LLaMA-Alpaca-2](https://github.com/ymcui/Chinese-LLaMA-Alpaca-2)的格式进行训练。
